package Pojos;
// Generated 1/11/2021 08:47:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer codigoCliente;
     private boolean estado;
     private String nombreCliente;
     private String apellidoCliente;
     private String direccionCliente;
     private String ciudadCliente;
     private Integer usuarioIngreso;
     private Date fechaIngreso;
     private Integer usuarioModificacion;
     private Date fechaModificacion;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Cliente() {
    }

	
    public Cliente(boolean estado, String nombreCliente, String apellidoCliente, String direccionCliente, String ciudadCliente) {
        this.estado = estado;
        this.nombreCliente = nombreCliente;
        this.apellidoCliente = apellidoCliente;
        this.direccionCliente = direccionCliente;
        this.ciudadCliente = ciudadCliente;
    }
    public Cliente(boolean estado, String nombreCliente, String apellidoCliente, String direccionCliente, String ciudadCliente, Integer usuarioIngreso, Date fechaIngreso, Integer usuarioModificacion, Date fechaModificacion, Set<Pedido> pedidos) {
       this.estado = estado;
       this.nombreCliente = nombreCliente;
       this.apellidoCliente = apellidoCliente;
       this.direccionCliente = direccionCliente;
       this.ciudadCliente = ciudadCliente;
       this.usuarioIngreso = usuarioIngreso;
       this.fechaIngreso = fechaIngreso;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
       this.pedidos = pedidos;
    }
   
    public Integer getCodigoCliente() {
        return this.codigoCliente;
    }
    
    public void setCodigoCliente(Integer codigoCliente) {
        this.codigoCliente = codigoCliente;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getApellidoCliente() {
        return this.apellidoCliente;
    }
    
    public void setApellidoCliente(String apellidoCliente) {
        this.apellidoCliente = apellidoCliente;
    }
    public String getDireccionCliente() {
        return this.direccionCliente;
    }
    
    public void setDireccionCliente(String direccionCliente) {
        this.direccionCliente = direccionCliente;
    }
    public String getCiudadCliente() {
        return this.ciudadCliente;
    }
    
    public void setCiudadCliente(String ciudadCliente) {
        this.ciudadCliente = ciudadCliente;
    }
    public Integer getUsuarioIngreso() {
        return this.usuarioIngreso;
    }
    
    public void setUsuarioIngreso(Integer usuarioIngreso) {
        this.usuarioIngreso = usuarioIngreso;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Integer getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(Integer usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


