package Pojos;
// Generated 1/11/2021 08:47:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer noFactura;
     private Cliente cliente;
     private Usuario usuario;
     private boolean estado;
     private Date fecha;
     private Date fechaIngreso;
     private Integer usuarioModificacion;
     private Date fechaModificacion;
     private Set<PedidoDetalle> pedidoDetalles = new HashSet<PedidoDetalle>(0);

    public Pedido() {
    }

	
    public Pedido(Cliente cliente, boolean estado) {
        this.cliente = cliente;
        this.estado = estado;
    }
    public Pedido(Cliente cliente, Usuario usuario, boolean estado, Date fecha, Date fechaIngreso, Integer usuarioModificacion, Date fechaModificacion, Set<PedidoDetalle> pedidoDetalles) {
       this.cliente = cliente;
       this.usuario = usuario;
       this.estado = estado;
       this.fecha = fecha;
       this.fechaIngreso = fechaIngreso;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
       this.pedidoDetalles = pedidoDetalles;
    }
   
    public Integer getNoFactura() {
        return this.noFactura;
    }
    
    public void setNoFactura(Integer noFactura) {
        this.noFactura = noFactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Integer getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(Integer usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<PedidoDetalle> getPedidoDetalles() {
        return this.pedidoDetalles;
    }
    
    public void setPedidoDetalles(Set<PedidoDetalle> pedidoDetalles) {
        this.pedidoDetalles = pedidoDetalles;
    }




}


