package Pojos;
// Generated 1/11/2021 08:47:37 PM by Hibernate Tools 4.3.1



/**
 * PedidoDetalleId generated by hbm2java
 */
public class PedidoDetalleId  implements java.io.Serializable {


     private int noFactura;
     private int codigoProducto;

    public PedidoDetalleId() {
    }

    public PedidoDetalleId(int noFactura, int codigoProducto) {
       this.noFactura = noFactura;
       this.codigoProducto = codigoProducto;
    }
   
    public int getNoFactura() {
        return this.noFactura;
    }
    
    public void setNoFactura(int noFactura) {
        this.noFactura = noFactura;
    }
    public int getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(int codigoProducto) {
        this.codigoProducto = codigoProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PedidoDetalleId) ) return false;
		 PedidoDetalleId castOther = ( PedidoDetalleId ) other; 
         
		 return (this.getNoFactura()==castOther.getNoFactura())
 && (this.getCodigoProducto()==castOther.getCodigoProducto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNoFactura();
         result = 37 * result + this.getCodigoProducto();
         return result;
   }   


}


