package Pojos;
// Generated 1/11/2021 08:47:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer codigoUsuario;
     private boolean estado;
     private String usuario;
     private String contrasenia;
     private Integer usuarioIngreso;
     private Date fechaIngreso;
     private Integer usuarioModificacion;
     private Date fechaModificacion;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Usuario() {
    }

	
    public Usuario(boolean estado, String usuario, String contrasenia) {
        this.estado = estado;
        this.usuario = usuario;
        this.contrasenia = contrasenia;
    }
    public Usuario(boolean estado, String usuario, String contrasenia, Integer usuarioIngreso, Date fechaIngreso, Integer usuarioModificacion, Date fechaModificacion, Set<Pedido> pedidos) {
       this.estado = estado;
       this.usuario = usuario;
       this.contrasenia = contrasenia;
       this.usuarioIngreso = usuarioIngreso;
       this.fechaIngreso = fechaIngreso;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
       this.pedidos = pedidos;
    }
   
    public Integer getCodigoUsuario() {
        return this.codigoUsuario;
    }
    
    public void setCodigoUsuario(Integer codigoUsuario) {
        this.codigoUsuario = codigoUsuario;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Integer getUsuarioIngreso() {
        return this.usuarioIngreso;
    }
    
    public void setUsuarioIngreso(Integer usuarioIngreso) {
        this.usuarioIngreso = usuarioIngreso;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Integer getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(Integer usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


